Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,11 +23,11 @@ jobs:
     - stage: server
       script:
         - cd ./server && npm install && npm run travis
-    - stage: "Markdown link checks"
-       script:
-        - remark -u validate-links .
-        - |
-          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l` &&
-          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
-            exit 1;
-          fi    
+#    - stage: "Markdown link checks"
+#      script:
+#        - remark -u validate-links .
+#        - |
+#          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l` &&
+#          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
+#            exit 1;
+#          fi    
